
### USERS (NOT authorized)
GET http://localhost:4500/users

### USERS (authorized)
GET http://localhost:4500/users
Authorization: s3cr3t


### Get all guests
GET http://localhost:4500/guests

### Get ONE guest (existing)
GET http://localhost:4500/guests/1

### Get ONE (test 22)
GET http://localhost:4500/guests/22

### Get ONE guest (ERROR)
GET http://localhost:4500/guests/231


### Get CONFIRMED guests
GET http://localhost:4500/guests?status=confirmed&test=123


### Get UNCONFIRMED guests
GET http://localhost:4500/guests?status=unconfirmed

### Get not-existent Status guests
GET http://localhost:4500/guests?status=xxxx