
#  Test endpoint /user
GET http://localhost:3035/users
Content-Type: application/json


### test endpoint /
GET http://localhost:3035/



### Show all products
GET http://localhost:3035/products


### Show shop name
GET http://localhost:3035/shop-info


### Test 404
GET http://localhost:3035/hello